# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chicago}
  s.version = "0.0.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Roland Swingler}]
  s.date = %q{2011-11-29}
  s.description = %q{Simple Data Warehouse toolkit}
  s.email = %q{roland.swingler@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "Rakefile",
    "chicago.gemspec",
    "lib/chicago.rb",
    "lib/chicago/core_ext/array.rb",
    "lib/chicago/core_ext/sequel/dataset.rb",
    "lib/chicago/data/month.rb",
    "lib/chicago/data/pivoted_dataset.rb",
    "lib/chicago/definable.rb",
    "lib/chicago/etl/batch.rb",
    "lib/chicago/etl/database_source.rb",
    "lib/chicago/etl/table_builder.rb",
    "lib/chicago/etl/task_invocation.rb",
    "lib/chicago/query.rb",
    "lib/chicago/rake_tasks.rb",
    "lib/chicago/schema/column.rb",
    "lib/chicago/schema/column_group_builder.rb",
    "lib/chicago/schema/constants.rb",
    "lib/chicago/schema/dimension.rb",
    "lib/chicago/schema/fact.rb",
    "lib/chicago/schema/hierarchical_element.rb",
    "lib/chicago/schema/migration_file_writer.rb",
    "lib/chicago/schema/star_schema_table.rb",
    "lib/chicago/schema/type_converters.rb",
    "lib/chicago/util/filter_string_parser.rb",
    "lib/chicago/vendor/code_statistics.rb",
    "spec/core_ext/array_spec.rb",
    "spec/data/month_spec.rb",
    "spec/data/pivoted_dataset_spec.rb",
    "spec/db_connections.yml.dist",
    "spec/etl/batch_spec.rb",
    "spec/etl/database_source_spec.rb",
    "spec/etl/table_builder_spec.rb",
    "spec/etl/task_spec.rb",
    "spec/query_spec.rb",
    "spec/schema/column_group_builder_spec.rb",
    "spec/schema/column_spec.rb",
    "spec/schema/db_type_converter_spec.rb",
    "spec/schema/dimension_spec.rb",
    "spec/schema/fact_spec.rb",
    "spec/schema/heirarchy_spec.rb",
    "spec/schema/migration_file_writer_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/matchers/be_one_of.rb",
    "spec/util/filter_string_parser_spec.rb",
    "tasks/stats.rake"
  ]
  s.homepage = %q{http://knaveofdiamonds.com}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Chicago}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel_migration_builder>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<mysql>, ["= 2.8.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 2.4.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<sequel_migration_builder>, ["~> 0.3.0"])
      s.add_dependency(%q<mysql>, ["= 2.8.1"])
      s.add_dependency(%q<rdoc>, ["~> 2.4.2"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<sequel_migration_builder>, ["~> 0.3.0"])
    s.add_dependency(%q<mysql>, ["= 2.8.1"])
    s.add_dependency(%q<rdoc>, ["~> 2.4.2"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

