require "spec_helper"

describe Chicago::Database::MigrationFileWriter do
  before :each do
    @mock_db = double(:db)
    @mock_db.stub(:database_type).and_return(:generic)
    @builder = described_class.new(@mock_db, "schema")
  end

  it "should return a migration file name using the timestamp of now" do
    now = Time.local(2010, 1, 1, 12, 30)
    Time.should_receive(:now).and_return(now)
    @builder.migration_file.should == "schema/20100101123000_auto_migration.rb"
  end

  it "should write out a migration file generated by Sequel::MigrationBuilder" do
    schema = double(:schema)

    generator = double(:generator)
    generator.should_receive(:traverse).
      with(schema).and_return(:table => :definitions)
    Chicago::Database::SchemaGenerator.stub(:new).and_return(generator)

    migration_builder = double(:migration_builder)
    migration_builder.should_receive(:generate_migration).
      with(:table => :definitions).and_return("migration content")
    Sequel::MigrationBuilder.stub(:new).and_return(migration_builder)

    file = StringIO.new
    File.stub(:open).and_yield(file)

    @builder.write_migration_file(schema)

    file.rewind
    file.read.should == "migration content"
  end
end
