require "spec_helper"

describe Chicago::Database::MigrationFileWriter do
  let(:db) { double(:db, :database_type => :generic) }

  it "returns a migration file name with the current timestamp" do
    Timecop.freeze(2010, 1, 1, 12, 30)
    subject.migration_file("schema").
      should == "schema/20100101123000_auto_migration.rb"
  end

  it "should write out a migration file generated by Sequel::MigrationBuilder" do
    schema = double(:schema)

    generator = double(:generator)
    generator.should_receive(:traverse).
      with(schema).and_return(:table => :definitions)
    Chicago::Database::SchemaGenerator.stub(:new).and_return(generator)

    migration_builder = double(:migration_builder)
    migration_builder.should_receive(:generate_migration).
      with(:table => :definitions).and_return("migration content")
    Sequel::MigrationBuilder.stub(:new).and_return(migration_builder)

    file = StringIO.new
    File.stub(:open).and_yield(file)

    subject.write_migration_file(db, schema, "directory")

    file.rewind
    file.read.should == "migration content"
  end
end
